### PR TITLE
Better abstractor docs

### PR DESCRIPTION
**Pull request by CosmoMyzrailGorynych**
- gotcha about file and field name match requrement (it consumed much time to understand it by myself);
- sample code to support different languages
- pro tip for use with arrays and nested structures

There must be a better way to do multilingual support in abstractors, right?

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
A preview of my changes (JSON strings are not quite readable):

image

- - -

- - -

- - -

image

**Comment by karneaud** [comment]
Is there any update/ feedback to this?

**Comment by Gottwik** [comment]
Hey, my bad for not merging right away. Great job on the changes!

**Comment by karneaud** [comment]
@Gottwik after looking at the app.js....this might not be best as @CosmoMyzrailGorynych is using mongodb instead of url

**Comment by CosmoMyzrailGorynych** [comment]
@karneaud pardon???

**Pull request merged**
